# Hound configuration
# Project uses ruff for linting, not flake8
# Disabling Hound to avoid conflicts with project's linting setup

python:
  enabled: false

flake8:
  enabled: false

fail_on_violations: false
