default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: no-commit-to-branch # prevent direct commits to main branch
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: ruff check
        name: Ruff check
        entry: nox
        args: [-s, ruff_check]
        language: system
        types: [python]
      - id: isort check
        name: isort check
        entry: nox
        args: [ -s, isort_check]
        language: system
        types: [python]
