coverage:
  status:
    project: off
  range: 50..100

github_checks:
  annotations: false

ignore:
  - "maya_umbrella/hooks"
  - "noxfile.py"
  - "maya_umbrella/_vendor/*"
  - "tests/*"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
