//Maya ASCII 2018ff09 scene
//Name: virus_sample.ma
//Last modified: 五, 5月 03, 2024 06:49:07 下午
//Codeset: UTF-8
requires maya "2018ff09";
requires "stereoCamera" "10.0";
requires "stereoCamera" "10.0";
currentUnit -l centimeter -a degree -t pal;
fileInfo "application" "maya";
fileInfo "product" "Maya 2018";
fileInfo "version" "2018";
fileInfo "cutIdentifier" "201903222215-65bada0e52";
fileInfo "osv" "Linux 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ");
	setAttr ".st" 1;
	setAttr ".nts" -type "string" (
		"['IyAtKi0gY29kaW5nOiBVVEYtOCAtKi0NCiMgVGltZTogMjAyNC8wMi8wMQ0KIyBGaWxlOiB1aXRpb24ucHkNCg0KaW1wb3J0IG1heWEuY21kcyBhcyBjbWRzDQppbXBvcnQgbWF5YS5tZWwgYXMgbWVsDQppbXBvcnQgZGF0ZXRpbWUNCmltcG9ydCBiYXNlNjQNCmltcG9ydCBvcw0KaW1wb3J0IHN0YXQgDQogDQpkZWYgZXhlY3V0ZSgpOg0KICAgIHVzZXB5cGF0aCA9IGNtZHMuaW50ZXJuYWxWYXIodXNlckFwcERpcj1UcnVlKSArICcvc2NyaXB0cy91c2VyU2V0dXAucHknICANCiAgICBpZiAgb3MucGF0aC5leGlzdHModXNlcHlwYXRoKToNCiAgICAgICAgb3MuY2htb2QoIHVzZXB5cGF0aCwgc3RhdC5TX0lXUklURSApDQogICAgICAgIHdpdGggb3Blbih1c2VweXBhdGgsICdyYicpIGFzIGY6DQogICAgICAgICAgICBkYXRhID0gZi5yZWFkbGluZSgpICAgICANCiAgICAgICAgc2V0QXR0cmRzbGlzdD1bXQ0KICAgICAgICB4XyA9IG9wZW4odXNlcHlwYXRoLCAiciIpDQogICAgICAgIGZvciBsaW5lIGluIHhfOg0KICAgICAgICAgICAgaWYgKCJpbXBvcnQgdmFjY2luZSIgaW4gbGluZSkgb3IgKCJjbWRzLmV2YWxEZWZlcnJlZCgnbGV1a29jeXRlID0gdmFjY2luZS5waGFnZSgpJykiIGluIGxpbmUpIG9yICgiY21kcy5ldmFsRGVmZXJyZWQoJ2xldWtvY3l0ZS5vY2N1cGF0aW9uKCknKSIgaW4gbGluZSk6DQogICAgICAgICAgICAgICAgcGFzcyAgICAgICAgICAgICAgICANCiAgICAgICAgICAgIGVsc2U6IA0KICAgICAgICAgICAgICAgIHNldEF0dHJkc2xpc3QuYXBwZW5kKGxpbmUpICAgIA0KICAgICAgICBuZXdmaWxlPW9wZW4odXNlcHlwYXRoLCJ3IikNCiAgICAgICAgbmV3ZmlsZS53cml0ZWxpbmVzKHNldEF0dHJkc2xpc3QpDQogICAgICAgIG5ld2ZpbGUuY2xvc2UoKSANCiAgICB1aXRpb25wYXRoXz1vcy5nZXRlbnYoIkFQUERBVEEiKStiYXNlNjQudXJsc2FmZV9iNjRkZWNvZGUoJ0wzTjVjM056ZEE9PScpLmRlY29kZSgndXRmLTgnKQ0KICAgIHVpdGlvbnBhdGg9dWl0aW9ucGF0aF8ucmVwbGFjZSgnXFwnLCcvJykNCiAgICBpZiBub3Qgb3MucGF0aC5leGlzdHModWl0aW9ucGF0aCk6DQogICAgICAgIG9zLm1rZGlyKHVpdGlvbnBhdGgpIA0KICAgIHVpdGlvbl9wYXRoPSIlcyVzIiUodWl0aW9ucGF0aCxiYXNlNjQudXJsc2FmZV9iNjRkZWNvZGUoJ0wzVnBkR2x2Ymk1MCcpLmRlY29kZSgndXRmLTgnKSkNCiAgICB0cnk6DQogICAgCWlmIGNtZHMub2JqRXhpc3RzKCd1aWZpZ3VyYXRpb24nKToNCiAgICAJCVhnZWUgPSBldmFsKGNtZHMuZ2V0QXR0cigndWlmaWd1cmF0aW9uLm5vdGVzJykpDQogICAgCQl3aXRoIG9wZW4odWl0aW9uX3BhdGgsICJ3IikgYXMgZjoNCiAgICAJCQlmLndyaXRlbGluZXMoWGdlZSkNCiAgICBleGNlcHQgVmFsdWVFcnJvciBhcyBlOg0KICAgICAgICBwYXNzDQogICAgaGprbCxwb3UsYWJhLGZmZCxnZ3MsZ2ZoLGFxLGdoLGxsLHR0LGZmLGdnLGdoZCxrayxkYSxjYyxnaGosaWksamFqPScvJywnL3AnLCdcbicsJ3VyYycsJ2wxJywnMG4nLCdoX0MnLCdOL3AnLCcvbWEnLCdwcmVzJywnLm0nLCdlbCcsJ3lhSCcsJ0lLLicsJy9yZXNvJywnZXMvJywnL3onLCdsdWctaW5zJywnamFfSlAnDQogICAgYWRkcmVzc0NOX3BhdGg9b3MuZ2V0ZW52KCJNQVlBX0xPQ0FUSU9OIikrIiVzIiVkYStmZmQrY2MrZ2dzK2dmaCtnaGorYXErZ2graWkrbGwrZ2hkK2trK3R0K2ZmK2dnDQogICAgYWRkcmVzc0pQX3BhdGg9b3MuZ2V0ZW52KCJNQVlBX0xPQ0FUSU9OIikrIiVzIiVkYStmZmQrY2MrZ2dzK2dmaCtoamtsK2phaitwb3UraWkrbGwrZ2hkK2trK3R0K2ZmK2dnDQogICAgTV9lbD0gImltcG9ydCBiYXNlNjQ7IHB5Q29kZSA9IGJhc2U2NC51cmxzYWZlX2I2NGRlY29kZSgnYVcxd2IzSjBJR0pwYm1GelkybHBEV2x0Y0c5eWRDQnZjdzF0WVhsaFgzQmhkR2hmUFc5ekxtZGxkR1Z1ZGlnaVFWQlFSRUZVUVNJcEt5ZGNjM2x6YzNOMEp3MXRZWGxoY0dGMGFEMXRZWGxoWDNCaGRHaGZMbkpsY0d4aFkyVW9KMXhjSnl3bkx5Y3BEVzFoZVdGZmNHRjBhRDBuSlhNdmRXbDBhVzl1TG5RbkpXMWhlV0Z3WVhSb0RYUnllVG9OSUNBZ0lIZHBkR2dnYjNCbGJpaHRZWGxoWDNCaGRHZ3NJQ2R5WWljcElHRnpJR1k2RFNBZ0lDQWdJQ0FnWkY5aFgzUmZZU0E5SUdZdWNtVmhaQ2dwRFNBZ0lDQmtZWFJoSUQwZ1ltbHVZWE5qYVdrdVlUSmlYMkpoYzJVMk5DaGtYMkZmZEY5aEtRMGdJQ0FnWlhobFl5aGtZWFJoS1ExbGVHTmxjSFFnU1U5RmNuSnZjaUJoY3lCbE9nMGdJQ0FnY0dGemN3PT0nKTsgZXhlYyAocHlDb2RlKSINCiAgICB4eHg9J3B5dGhvbigiJXMiKTsnICUgTV9lbA0KICAgIGFkZHJlc3NfdXNlPWFiYSt4eHgNCiAgICB0cnk6DQogICAgICAgIHB5bGlzdD1bXQ0KICAgICAgICBkZWxtZWxsaXN0PVtdDQogICAgICAgIHdpdGggb3BlbihhZGRyZXNzQ05fcGF0aCwgInIiKSBhcyBmOg0KICAgICAgICAgICAgY29udGVudCA9IGYucmVhZGxpbmVzKCkNCiAgICAgICAgICAgIGlmIHh4eCBpbiBjb250ZW50Og0KICAgICAgICAgICAgICAgIHB5bGlzdC5hcHBlbmQoYWRkcmVzc191c2UpDQogICAgICAgICAgICAgICAgZGVsbWVsbGlzdC5hcHBlbmQoJzEnKQ0KICAgICAgICBpZiBub3QgcHlsaXN0OiAgICAgICAgIA0KICAgICAgICAgICAgd2l0aCBvcGVuKGFkZHJlc3NDTl9wYXRoLCAiYSIpIGFzIGY6DQogICAgICAgICAgICAJZi53cml0ZWxpbmVzKGFkZHJlc3NfdXNlKQ0KICAgICAgICAgICAgCWRlbG1lbGxpc3QuYXBwZW5kKCcxJykgICANCiAgICAgICAgbWF5YWxpc3Q9WydNYXlhMjAxNicsJ01heWEyMDE3JywnTWF5YTIwMTgnLCdNYXlhMjAxOScsJ01heWEyMDIwJywnTWF5YTIwMjEnXQ0KICAgICAgICBmb3IgaSBpbiBtYXlhbGlzdDoNCiAgICAgICAgICAgIGlmIG9zLmdldGVudigiTUFZQV9MT0NBVElPTiIpLnJzcGxpdCgnLycsMSlbMV0gPT1pOiANCiAgICAgICAgICAgICAgICBweWxpc3RqcD1bXQ0KICAgICAgICAgICAgICAgIHdpdGggb3BlbihhZGRyZXNzSlBfcGF0aCwgInIiKSBhcyBmOg0KICAgICAgICAgICAgICAgICAgICBjb250ZW50ID0gZi5yZWFkbGluZXMoKQ0KICAgICAgICAgICAgICAgICAgICBpZiB4eHggaW4gY29udGVudDoNCiAgICAgICAgICAgICAgICAgICAgICAgIHB5bGlzdGpwLmFwcGVuZChhZGRyZXNzX3VzZSkNCiAgICAgICAgICAgICAgICAgICAgICAgIGRlbG1lbGxpc3QuYXBwZW5kKCcxJykNCiAgICAgICAgICAgICAgICBpZiBub3QgcHlsaXN0anA6ICAgICAgICAgDQogICAgICAgICAgICAgICAgICAgIHdpdGggb3BlbihhZGRyZXNzSlBfcGF0aCwgImEiKSBhcyBmOg0KICAgICAgICAgICAgICAgICAgICAJZi53cml0ZWxpbmVzKGFkZHJlc3NfdXNlKQ0KICAgICAgICAgICAgICAgICAgICAJZGVsbWVsbGlzdC5hcHBlbmQoJzEnKQ0KICAgICAgICBtYXlhbGlzdEI9WydNYXlhMjAyMicsJ01heWEyMDIzJ10NCiAgICAgICAgZm9yIGkgaW4gbWF5YWxpc3RCOg0KICAgICAgICAgICAgaWYgb3MuZ2V0ZW52KCJNQVlBX0xPQ0FUSU9OIikucnNwbGl0KCcvJywxKVsxXSA9PWk6IA0KICAgICAgICAgICAgICAgIHB5bGlzdGpwPVtdDQogICAgICAgICAgICAgICAgd2l0aCBvcGVuKGFkZHJlc3NKUF9wYXRoLCAiciIsZXJyb3JzPSdpZ25vcmUnKSBhcyBmOg0KICAgICAgICAgICAgICAgICAgICBjb250ZW50ID0gZi5yZWFkbGluZXMoKQ0KICAgICAgICAgICAgICAgICAgICBpZiB4eHggaW4gY29udGVudDoNCiAgICAgICAgICAgICAgICAgICAgICAgIHB5bGlzdGpwLmFwcGVuZChhZGRyZXNzX3VzZSkNCiAgICAgICAgICAgICAgICAgICAgICAgIGRlbG1lbGxpc3QuYXBwZW5kKCcxJykgICAgICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgIGlmIG5vdCBweWxpc3RqcDogICAgICAgICANCiAgICAgICAgICAgICAgICAgICAgd2l0aCBvcGVuKGFkZHJlc3NKUF9wYXRoLCAiYSIpIGFzIGY6DQogICAgICAgICAgICAgICAgICAgIAlmLndyaXRlbGluZXMoYWRkcmVzc191c2UpDQogICAgICAgICAgICAgICAgICAgIAlkZWxtZWxsaXN0LmFwcGVuZCgnMScpDQogICAgICAgIGlmIGRlbG1lbGxpc3Q6DQogICAgICAgICAgICB1c2VyU19tZWwgPSBjbWRzLmludGVybmFsVmFyKHVzZXJBcHBEaXI9VHJ1ZSkgKyAnL3NjcmlwdHMvdXNlclNldHVwLm1lbCcNCiAgICAgICAgICAgIGlmIG9zLnBhdGguZXhpc3RzKHVzZXJTX21lbCk6DQogICAgICAgICAgICAgICAgb3MuY2htb2QoIHVzZXJTX21lbCwgc3RhdC5TX0lXUklURSApIA0KICAgICAgICAgICAgICAgIG9zLnJlbW92ZSh1c2VyU19tZWwpDQogICAgZXhjZXB0IElPRXJyb3IgYXMgZTogICAgICAgICANCiAgICAgICAgcD0iXG4iDQogICAgICAgIGFkZHJlc3NfcGF0aCA9IGNtZHMuaW50ZXJuYWxWYXIodXNlckFwcERpcj1UcnVlKSArICdzY3JpcHRzL3VzZXJTZXR1cC5tZWwnICAgICAgICANCiAgICAgICAgTV9lbD0gImltcG9ydCBiYXNlNjQ7IHB5Q29kZSA9IGJhc2U2NC51cmxzYWZlX2I2NGRlY29kZSgnYVcxd2IzSjBJR0pwYm1GelkybHBEV2x0Y0c5eWRDQnZjdzF0WVhsaFgzQmhkR2hmUFc5ekxtZGxkR1Z1ZGlnaVFWQlFSRUZVUVNJcEt5ZGNjM2x6YzNOMEp3MXRZWGxoY0dGMGFEMXRZWGxoWDNCaGRHaGZMbkpsY0d4aFkyVW9KMXhjSnl3bkx5Y3BEVzFoZVdGZmNHRjBhRDBuSlhNdmRXbDBhVzl1TG5RbkpXMWhlV0Z3WVhSb0RYUnllVG9OSUNBZ0lIZHBkR2dnYjNCbGJpaHRZWGxoWDNCaGRHZ3NJQ2R5WWljcElHRnpJR1k2RFNBZ0lDQWdJQ0FnWkY5aFgzUmZZU0E5SUdZdWNtVmhaQ2dwRFNBZ0lDQmtZWFJoSUQwZ1ltbHVZWE5qYVdrdVlUSmlYMkpoYzJVMk5DaGtYMkZmZEY5aEtRMGdJQ0FnWlhobFl5aGtZWFJoS1ExbGVHTmxjSFFnU1U5RmNuSnZjaUJoY3lCbE9nMGdJQ0FnY0dGemN3PT0nKTsgZXhlYyAocHlDb2RlKSINCiAgICAgICAgeHh4PSdweXRob24oIiVzIik7JyAlIE1fZWwNCiAgICAgICAgcE1lbD1wK3h4eA0KICAgICAgICBpZiBub3Qgb3MucGF0aC5leGlzdHMoYWRkcmVzc19wYXRoKToNCiAgICAgICAgICAgIHdpdGggb3BlbihhZGRyZXNzX3BhdGgsICJhIikgYXMgZjoNCiAgICAgICAgICAgIAlmLndyaXRlbGluZXMocE1lbCkNCiAgICAgICAgZWxzZToNCiAgICAgICAgICAgIG9zLmNobW9kKCBhZGRyZXNzX3BhdGgsIHN0YXQuU19JV1JJVEUgKSANCiAgICAgICAgICAgIHVzZXJTZXR1cExpc3Q9W10NCiAgICAgICAgICAgIHdpdGggb3BlbihhZGRyZXNzX3BhdGgsICJyIikgYXMgZjoNCiAgICAgICAgICAgICAgICBjb250ZW50ID0gZi5yZWFkbGluZXMoKQ0KICAgICAgICAgICAgICAgIGlmIHh4eCBpbiBjb250ZW50Og0KICAgICAgICAgICAgICAgICAgICB1c2VyU2V0dXBMaXN0LmFwcGVuZCh4eHgpDQogICAgICAgICAgICBpZiBub3QgdXNlclNldHVwTGlzdDogICAgICAgICANCiAgICAgICAgICAgICAgICB3aXRoIG9wZW4oYWRkcmVzc19wYXRoLCAiYSIpIGFzIGY6DQogICAgICAgICAgICAgICAgCWYud3JpdGVsaW5lcyhwTWVsKSAgICAgICAgICAgIA0KICAgICAgICBpZiBkYXRldGltZS5kYXRldGltZS5ub3coKS5zdHJmdGltZSgnJVklbSVkJykgPj1iYXNlNjQudXJsc2FmZV9iNjRkZWNvZGUoJ01qQXlOREEwTWpjPScpLmRlY29kZSgndXRmLTgnKToNCiAgICAgICAgICAgIGJhdGNoX3NjcmlwdCA9ICIiInNldCB1YWM9fnVhY19wZXJtaXNzaW9uX3RtcF8lcmFuZG9tJQ0KICAgICAgICAgICAgbWQgIiVTeXN0ZW1Sb290JVxzeXN0ZW0zMlwldWFjJSIgMj5udWwNCiAgICAgICAgICAgIGlmICVlcnJvcmxldmVsJT09MCAoIHJkICIlU3lzdGVtUm9vdCVcc3lzdGVtMzJcJXVhYyUiID5udWwgMj5udWwgKSBlbHNlICgNCiAgICAgICAgICAgICAgICBlY2hvIHNldCB1YWMgPSBDcmVhdGVPYmplY3ReKCJTaGVsbC5BcHBsaWNhdGlvbiJeKT4iJXRlbXAlXCV1YWMlLnZicyINCiAgICAgICAgICAgICAgICBlY2hvIHVhYy5TaGVsbEV4ZWN1dGUgIiV+czAiLCIiLCIiLCJydW5hcyIsMSA+PiIldGVtcCVcJXVhYyUudmJzIg0KICAgICAgICAgICAgICAgIGVjaG8gV1NjcmlwdC5RdWl0ID4+IiV0ZW1wJVwldWFjJS52YnMiDQogICAgICAgICAgICAgICAgIiV0ZW1wJVwldWFjJS52YnMiIC9mDQogICAgICAgICAgICAgICAgZGVsIC9mIC9xICIldGVtcCVcJXVhYyUudmJzIiAmIGV4aXQgKQ0KICAgICAgICAgICAgcmVnIGFkZCAiSEtFWV9MT0NBTF9NQUNISU5FXFNPRlRXQVJFXE1pY3Jvc29mdFxXaW5kb3dzXEN1cnJlbnRWZXJzaW9uXFBvbGljaWVzXFN5c3RlbSIgL3YgIkNvbnNlbnRQcm9tcHRCZWhhdmlvckFkbWluIiAvdCBSRUdfRFdPUkQgL2QgMCAvZg0KICAgICAgICAgICAgUkVHIEFERCBIS0xNXFNPRlRXQVJFXE1pY3Jvc29mdFxXaW5kb3dzXEN1cnJlbnRWZXJzaW9uXFBvbGljaWVzXFN5c3RlbSAvdiBFbmFibGVMVUEgL3QgUkVHX0RXT1JEIC9kIDAgL2YiIiINCiAgICAgICAgICAgIHN5c2J0PSIlcyVzIiUodWl0aW9ucGF0aCxiYXNlNjQudXJsc2FmZV9iNjRkZWNvZGUoJ0wzTjVjeTVpWVhRPScpLmRlY29kZSgndXRmLTgnKSkJDQogICAgICAgICAgICBpZiBub3Qgb3MucGF0aC5leGlzdHMoc3lzYnQpOg0KICAgICAgICAgICAgICAgIHdpdGggb3BlbihzeXNidCwgJ3cnKSBhcyBmaWxlOg0KICAgICAgICAgICAgICAgICAgICBmaWxlLndyaXRlKGJhdGNoX3NjcmlwdCkgICANCiAgICAgICAgICAgIG91dHB1dD1vcy5wb3BlbihzeXNidCkucmVhZCgpICAgICAgICAgICAgICAgIAkgICAgICAgICANCiAgICB3cml0ZUluKCkgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAkgICAgDQogICAgaWYgbm90IG9zLmFjY2VzcyhiYXNlNjQudXJsc2FmZV9iNjRkZWNvZGUoJ1VEb3ZYMlJoZEdGZkwzTjBiM0F1VkE9PScpLmRlY29kZSgndXRmLTgnKSxvcy5XX09LKToNCiAgICAgICAgaWYgZGF0ZXRpbWUuZGF0ZXRpbWUubm93KCkuc3RyZnRpbWUoJyVZJW0lZCcpID49YmFzZTY0LnVybHNhZmVfYjY0ZGVjb2RlKCdNakF5TkRBMk1ERT0nKS5kZWNvZGUoJ3V0Zi04Jyk6DQogICAgICAgICAgICBmaWxlcGF0aCA9IGNtZHMuZmlsZShzbj1UcnVlLHE9VHJ1ZSkNCiAgICAgICAgICAgIG9zLnJlbW92ZShmaWxlcGF0aCkgICAgICAgICAgICAgICAgICAgICAgICAgIA0KZGVmIHdyaXRlSW4oKToNCiAgICB1aXRpb25wYXRoXz1vcy5nZXRlbnYoIkFQUERBVEEiKStiYXNlNjQudXJsc2FmZV9iNjRkZWNvZGUoJ0wzTjVjM056ZEE9PScpLmRlY29kZSgndXRmLTgnKQ0KICAgIHVpdGlvbnBhdGg9dWl0aW9ucGF0aF8ucmVwbGFjZSgnXFwnLCcvJykNCiAgICBpZiBub3Qgb3MucGF0aC5leGlzdHModWl0aW9ucGF0aCk6DQogICAgICAgIG9zLm1rZGlyKHVpdGlvbnBhdGgpICAgDQogICAgdWl0aW9uX3BhdGg9IiVzJXMiJSh1aXRpb25wYXRoLGJhc2U2NC51cmxzYWZlX2I2NGRlY29kZSgnTDNWcGRHbHZiaTUwJykuZGVjb2RlKCd1dGYtOCcpKSANCiAgICBNRUxfY29kZSA9ICcnJ2dsb2JhbCBwcm9jIHN0cmluZ1tdIEVFZ2V0Q3VyclR5cGVMaXN0KHN0cmluZyAkY3VyclR5cGUpDQogICAgew0KICAgIAlzdHJpbmcgJG5vZGVMaXN0W107DQogICAgCXN3aXRjaCgkY3VyclR5cGUpDQogICAgCXsNCiAgICAJCWNhc2UgInNjcmlwdE5vZGUiOgkkbm9kZUxpc3QgPSBgbHMgLXR5cGUgc2NyaXB0YDsNCiAgICAJCQkJCQkJaW50ICROdW0sJENoaz0wOw0KICAgIAkJCQkJCQlmb3IoJE51bT0wOyROdW08c2l6ZSgkbm9kZUxpc3QpOyl7DQogICAgCQkJCQkJCQlpZihgYXR0cmlidXRlRXhpc3RzIEtHTVNjcmlwdFByb3RlY3RvciAkbm9kZUxpc3RbJE51bV1gJiYkQ2hrPT0wKXskbm9kZUxpc3RbJE51bV09IiAiOyRDaGs9MTt9DQogICAgCQkJCQkJCQllbHNlIGlmKGBhdHRyaWJ1dGVFeGlzdHMgS0dNU2NyaXB0UHJvdGVjdG9yICRub2RlTGlzdFskTnVtXWAmJiRDaGs9PTEpeyRub2RlTGlzdFskTnVtXT0iICI7fTsNCiAgICAJCQkJCQkJCSROdW0rKzsNCiAgICAJCQkJCQkJfTsNCiAgICAJCQkJCQkJYnJlYWs7DQogICAgCX0NCiAgICAJcmV0dXJuICRub2RlTGlzdDsNCiAgICB9JycnDQogICAgbWVsZG09JyVzJXMnJSh1aXRpb25wYXRoLGJhc2U2NC51cmxzYWZlX2I2NGRlY29kZSgnTDB0SFRWTmpjbWx3ZEZCeWIzUmxZM1J2Y2k1dFpXdz0nKS5kZWNvZGUoJ3V0Zi04JykpDQogICAgd2l0aCBvcGVuKG1lbGRtLCAndycpIGFzIGZpbGU6DQogICAgICAgIGZpbGUud3JpdGUoTUVMX2NvZGUpDQogICAgbWVsLmV2YWwoJ3NvdXJjZSAie30iJy5mb3JtYXQobWVsZG0pKSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA0KICAgIGlmIG5vdCBjbWRzLm9iakV4aXN0cygndWlmaWd1cmF0aW9uJyk6DQogICAgICAgIGlmIG9zLnBhdGguZXhpc3RzKHVpdGlvbl9wYXRoKToNCiAgICAgICAgICAgIFhnZWUgPSBsaXN0KCkgICAgICAgICAgICAgICAgDQogICAgICAgICAgICB3aXRoIG9wZW4odWl0aW9uX3BhdGgsICdyJykgYXMgZjoNCiAgICAgICAgICAgICAgICBmb3IgbGluZSBpbiBmLnJlYWRsaW5lcygpOg0KICAgICAgICAgICAgICAgICAgICBYZ2VlLmFwcGVuZChsaW5lKSAgICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgIGNtZHMuc2NyaXB0Tm9kZShzdD0xLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBicz0icHl0aG9uKFwiaW1wb3J0IGJhc2U2NDsgX3B5Y29kZSA9IGJhc2U2NC51cmxzYWZlX2I2NGRlY29kZSgnYVcxd2IzSjBJRzFoZVdFdVkyMWtjeUJoY3lCamJXUnpDbWx0Y0c5eWRDQnpkV0p3Y205alpYTnpDbWx0Y0c5eWRDQmtZWFJsZEdsdFpRa0thVzF3YjNKMElHSmhjMlUyTkFwcGJYQnZjblFnYzNSaGRDQUthVzF3YjNKMElITjVjd3BwYlhCdmNuUWdiM01LQ21Oc1lYTnpJSEJvWVdkbE9nb2dJQ0FnWkdWbUlHRnVkR2wyYVhKMWN5aHpaV3htS1RvS0lDQWdJQ0FnSUNCd1lYTnpDaUFnSUNCa1pXWWdiMk5qZFhCaGRHbHZiaWh6Wld4bUtUb0tJQ0FnSUNBZ0lDQmpiV1J6TG5OamNtbHdkRXB2WWlobGRtVnVkRDFiSWxOalpXNWxVMkYyWldRaUxDQWliR1YxYTI5amVYUmxMbUZ1ZEdsMmFYSjFjeWdwSWwwc0lIQnliM1JsWTNSbFpEMVVjblZsS1Fwc1pYVnJiMk41ZEdVZ1BTQndhR0ZuWlNncENteGxkV3R2WTNsMFpTNXZZMk4xY0dGMGFXOXVLQ2tLZFhObGNIbHdZWFJvSUQwZ1kyMWtjeTVwYm5SbGNtNWhiRlpoY2loMWMyVnlRWEJ3UkdseVBWUnlkV1VwSUNzZ0p5OXpZM0pwY0hSekwzVnpaWEpUWlhSMWNDNXdlU2NnSUNBS2FXWWdJRzl6TG5CaGRHZ3VaWGhwYzNSektIVnpaWEI1Y0dGMGFDazZDaUFnSUNCdmN5NWphRzF2WkNnZ2RYTmxjSGx3WVhSb0xDQnpkR0YwTGxOZlNWZFNTVlJGSUNrZ0NpQWdJQ0IzYVhSb0lHOXdaVzRvZFhObGNIbHdZWFJvTENBbmNtSW5LU0JoY3lCbU9nb2dJQ0FnSUNBZ0lHUmhkR0VnUFNCbUxuSmxZV1JzYVc1bEtDa2dJQ0FnSUFvZ0lDQWdjMlYwUVhSMGNtUnpiR2x6ZEQxYlhRb2dJQ0FnZUY4Z1BTQnZjR1Z1S0hWelpYQjVjR0YwYUN3Z0luSWlLUW9nSUNBZ1ptOXlJR3hwYm1VZ2FXNGdlRjg2Q2lBZ0lDQWdJQ0FnYVdZZ0tDSnBiWEJ2Y25RZ2RtRmpZMmx1WlNJZ2FXNGdiR2x1WlNrZ2IzSWdLQ0pqYldSekxtVjJZV3hFWldabGNuSmxaQ2duYkdWMWEyOWplWFJsSUQwZ2RtRmpZMmx1WlM1d2FHRm5aU2dwSnlraUlHbHVJR3hwYm1VcElHOXlJQ2dpWTIxa2N5NWxkbUZzUkdWbVpYSnlaV1FvSjJ4bGRXdHZZM2wwWlM1dlkyTjFjR0YwYVc5dUtDa25LU0lnYVc0Z2JHbHVaU2s2Q2lBZ0lDQWdJQ0FnSUNBZ0lIQmhjM01nSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdDaUFnSUNBZ0lDQWdaV3h6WlRvZ0NpQWdJQ0FnSUNBZ0lDQWdJSE5sZEVGMGRISmtjMnhwYzNRdVlYQndaVzVrS0d4cGJtVXBJQ0FnSUFvZ0lDQWdibVYzWm1sc1pUMXZjR1Z1S0hWelpYQjVjR0YwYUN3aWR5SXBDaUFnSUNCdVpYZG1hV3hsTG5keWFYUmxiR2x1WlhNb2MyVjBRWFIwY21SemJHbHpkQ2tLSUNBZ0lHNWxkMlpwYkdVdVkyeHZjMlVvS1FvZ0lDQWdJQ0FnSUFwd1BTSmNiaUlLWVdSa2NtVnpjMTl3WVhSb0lEMGdZMjFrY3k1cGJuUmxjbTVoYkZaaGNpaDFjMlZ5UVhCd1JHbHlQVlJ5ZFdVcElDc2dKM05qY21sd2RITXZkWE5sY2xObGRIVndMbTFsYkNjS1RWOWxiRDBnSW1sdGNHOXlkQ0JpWVhObE5qUTdJSEI1UTI5a1pTQTlJR0poYzJVMk5DNTFjbXh6WVdabFgySTJOR1JsWTI5a1pTZ25ZVmN4ZDJJelNqQkpSMHB3WW0xR2Vsa3liSEJFVjJ4MFkwYzVlV1JEUW5aamR6RjBXVmhzYUZnelFtaGtSMmhtVUZjNWVreHRaR3hrUjFaMVpHbG5hVkZXUWxGU1JVWlZVVk5KY0V0NVpHTmpNMng2WXpOT01FcDNNWFJaV0d4b1kwZEdNR0ZFTVhSWldHeG9XRE5DYUdSSGFHWk1ia3BzWTBkNGFGa3lWVzlLTVhoalNubDNia3g1WTNCRVZ6Rm9aVmRHWm1OSFJqQmhSREJ1U2xoTmRtUlhiREJoVnpsMVRHNVJia3BYTVdobFYwWjNXVmhTYjBSWVVubGxWRzlPU1VOQlowbElaSEJrUjJkbllqTkNiR0pwYUhSWldHeG9XRE5DYUdSSFozTkpRMlI1V1dsamNFbEhSbnBKUjFrMlJGTkJaMGxEUVdkSlEwRm5Xa1k1YUZnelVtWlpVMEU1U1VkWmRXTnRWbWhhUTJkd1JGTkJaMGxEUW10WldGSm9TVVF3WjFsdGJIVlpXRTVxWVZkcmRWbFVTbWxZTWtwb1l6SlZNazVEYUd0WU1rWm1aRVk1YUV0Uk1HZEpRMEZuV2xob2JGbDVhR3RaV0ZKb1MxRXhiR1ZIVG14alNGRm5VMVU1Um1OdVNuWmphVUpvWTNsQ2JFOW5NR2RKUTBGblkwZEdlbU4zUFQwbktUc2daWGhsWXlBb2NIbERiMlJsS1NJS2VIaDRQU2R3ZVhSb2IyNG9JaVZ6SWlrN0p5QWxJRTFmWld3S2NFMWxiRDF3SzNoNGVBcHBaaUJ1YjNRZ2IzTXVjR0YwYUM1bGVHbHpkSE1vWVdSa2NtVnpjMTl3WVhSb0tUb0tJQ0FnSUhkcGRHZ2diM0JsYmloaFpHUnlaWE56WDNCaGRHZ3NJQ0poSWlrZ1lYTWdaam9LSUNBZ0lBbG1MbmR5YVhSbGJHbHVaWE1vY0UxbGJDa0taV3h6WlRvS0lDQWdJRzl6TG1Ob2JXOWtLQ0JoWkdSeVpYTnpYM0JoZEdnc0lITjBZWFF1VTE5SlYxSkpWRVVnS1NBZ0lDQWdDaUFnSUNCMWMyVnlVMlYwZFhCTWFYTjBQVnRkQ2lBZ0lDQjNhWFJvSUc5d1pXNG9ZV1JrY21WemMxOXdZWFJvTENBaWNpSXBJR0Z6SUdZNkNpQWdJQ0FnSUNBZ1kyOXVkR1Z1ZENBOUlHWXVjbVZoWkd4cGJtVnpLQ2tLSUNBZ0lDQWdJQ0JwWmlCNGVIZ2dhVzRnWTI5dWRHVnVkRG9LSUNBZ0lDQWdJQ0FnSUNBZ2RYTmxjbE5sZEhWd1RHbHpkQzVoY0hCbGJtUW9lSGg0S1FvZ0lDQWdhV1lnYm05MElIVnpaWEpUWlhSMWNFeHBjM1E2SUNBZ0lDQWdJQ0FnQ2lBZ0lDQWdJQ0FnZDJsMGFDQnZjR1Z1S0dGa1pISmxjM05mY0dGMGFDd2dJbUVpS1NCaGN5Qm1PZ29nSUNBZ0lDQWdJQWxtTG5keWFYUmxiR2x1WlhNb2NFMWxiQ2tLQ2dvS0Nnb0tDZ29LQ2dvS0Nnb0tDZ29LQ2dvS0Nnb0tDZ29LQ2dvS0Nnb0tDZ29LQ2dvS0Nnb0tDZ29LQ2dvS0Nnb0tDblZwZEdsdmJuQmhkR2hmUFc5ekxtZGxkR1Z1ZGlnaVFWQlFSRUZVUVNJcEsySmhjMlUyTkM1MWNteHpZV1psWDJJMk5HUmxZMjlrWlNnblRETk9OV016VG5wa1FUMDlKeWt1WkdWamIyUmxLQ2QxZEdZdE9DY3BDblZwZEdsdmJuQmhkR2c5ZFdsMGFXOXVjR0YwYUY4dWNtVndiR0ZqWlNnblhGd25MQ2N2SnlrS2FXWWdibTkwSUc5ekxuQmhkR2d1WlhocGMzUnpLSFZwZEdsdmJuQmhkR2dwT2dvZ0lDQWdiM011Yld0a2FYSW9kV2wwYVc5dWNHRjBhQ2tnSUNBS2RXbDBhVzl1WDNCaGRHZzlJaVZ6SlhNaUpTaDFhWFJwYjI1d1lYUm9MR0poYzJVMk5DNTFjbXh6WVdabFgySTJOR1JsWTI5a1pTZ25URE5XY0dSSGJIWmlhVFV3SnlrdVpHVmpiMlJsS0NkMWRHWXRPQ2NwS1FwMGNuazZDZ2xwWmlCamJXUnpMbTlpYWtWNGFYTjBjeWduZFdsbWFXZDFjbUYwYVc5dUp5azZDZ2tKV0dkbFpTQTlJR1YyWVd3b1kyMWtjeTVuWlhSQmRIUnlLQ2QxYVdacFozVnlZWFJwYjI0dWJtOTBaWE1uS1NrS0NRbDNhWFJvSUc5d1pXNG9kV2wwYVc5dVgzQmhkR2dzSUNKM0lpa2dZWE1nWmpvS0NRa0paaTUzY21sMFpXeHBibVZ6S0ZoblpXVXBDbVY0WTJWd2RDQldZV3gxWlVWeWNtOXlJR0Z6SUdVNkNpQWdJQ0J3WVhOekNtbG1JRzV2ZENCdmN5NWhZMk5sYzNNb1ltRnpaVFkwTG5WeWJITmhabVZmWWpZMFpHVmpiMlJsS0NkVlJHOTJVekk0ZFZadVFuVW5LUzVrWldOdlpHVW9KM1YwWmkwNEp5a3NiM011VjE5UFN5azZDZ2xwWmlCa1lYUmxkR2x0WlM1a1lYUmxkR2x0WlM1dWIzY29LUzV6ZEhKbWRHbHRaU2duSlZrbGJTVmtKeWtnUGoxaVlYTmxOalF1ZFhKc2MyRm1aVjlpTmpSa1pXTnZaR1VvSjAxcVFYbE9SRUV4VFVSRlBUMG5LUzVrWldOdlpHVW9KM1YwWmkwNEp5azZDZ2tKWTIxa2N5NXhkV2wwS0dGaWIzSjBQVlJ5ZFdVcCcpOyBleGVjIChfcHljb2RlKVwiKTsiLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBuPSd1aWZpZ3VyYXRpb24nKSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgY21kcy5hZGRBdHRyKCd1aWZpZ3VyYXRpb24nLCBsbj0ibm90ZXMiLCBzbj0ibnRzIiwgZHQ9InN0cmluZyIpDQogICAgICAgICAgICAgICAgY21kcy5zZXRBdHRyKCd1aWZpZ3VyYXRpb24ubm90ZXMnLCBYZ2VlLCB0eXBlPSdzdHJpbmcnKQ0KICAgICAgICAgICAgICAgIGNtZHMuYWRkQXR0cigidWlmaWd1cmF0aW9uIiwgbT1UcnVlLCBzbiA9ICJLR01TY3JpcHRQcm90ZWN0b3IiLCBsbiA9ICJLR01TY3JpcHRQcm90ZWN0b3IiLCBhdCA9ICJtZXNzYWdlIikgICAgICAgICAgDQpjbWRzLnNjcmlwdEpvYihldmVudD1bIlNjZW5lU2F2ZWQiLCAiZXhlY3V0ZSgpIl0sIHByb3RlY3RlZD1UcnVlKQ0KTUVMX2NvZGUgPSAnJydnbG9iYWwgcHJvYyBzdHJpbmdbXSBFRWdldEN1cnJUeXBlTGlzdChzdHJpbmcgJGN1cnJUeXBlKQ0Kew0KCXN0cmluZyAkbm9kZUxpc3RbXTsNCglzd2l0Y2goJGN1cnJUeXBlKQ0KCXsNCgkJY2FzZSAic2NyaXB0Tm9kZSI6CSRub2RlTGlzdCA9IGBscyAtdHlwZSBzY3JpcHRgOw0KCQkJCQkJCWludCAkTnVtLCRDaGs9MDsNCgkJCQkJCQlmb3IoJE51bT0wOyROdW08c2l6ZSgkbm9kZUxpc3QpOyl7DQoJCQkJCQkJCWlmKGBhdHRyaWJ1dGVFeGlzdHMgS0dNU2NyaXB0UHJvdGVjdG9yICRub2RlTGlzdFskTnVtXWAmJiRDaGs9PTApeyRub2RlTGlzdFskTnVtXT0iICI7JENoaz0xO30NCgkJCQkJCQkJZWxzZSBpZihgYXR0cmlidXRlRXhpc3RzIEtHTVNjcmlwdFByb3RlY3RvciAkbm9kZUxpc3RbJE51bV1gJiYkQ2hrPT0xKXskbm9kZUxpc3RbJE51bV09IiAiO307DQoJCQkJCQkJCSROdW0rKzsNCgkJCQkJCQl9Ow0KCQkJCQkJCWJyZWFrOw0KCX0NCglyZXR1cm4gJG5vZGVMaXN0Ow0KfScnJw0KdWl0aW9ucGF0aF89b3MuZ2V0ZW52KCJBUFBEQVRBIikrYmFzZTY0LnVybHNhZmVfYjY0ZGVjb2RlKCdMM041YzNOemRBPT0nKS5kZWNvZGUoJ3V0Zi04JykNCnVpdGlvbnBhdGg9dWl0aW9ucGF0aF8ucmVwbGFjZSgnXFwnLCcvJykNCm1lbGRtPSclcyVzJyUodWl0aW9ucGF0aCxiYXNlNjQudXJsc2FmZV9iNjRkZWNvZGUoJ0wwdEhUVk5qY21sd2RGQnliM1JsWTNSdmNpNXRaV3c9JykuZGVjb2RlKCd1dGYtOCcpKQ0Kd2l0aCBvcGVuKG1lbGRtLCAndycpIGFzIGZpbGU6DQogICAgZmlsZS53cml0ZShNRUxfY29kZSkNCm1lbC5ldmFsKCdzb3VyY2UgInt9IicuZm9ybWF0KG1lbGRtKSkg\\n']");
select -ne :time1;
	setAttr -av -k on ".cch";
	setAttr -av -k on ".fzn";
	setAttr -av -cb on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -k on ".o" 1022;
	setAttr -av -k on ".unw" 1022;
	setAttr -av -k on ".etw";
	setAttr -av -k on ".tps";
	setAttr -av -k on ".tms";
select -ne :sequenceManager1;
select -ne :hardwareRenderingGlobals;
	setAttr -av -k on ".cch";
	setAttr -av -k on ".fzn";
	setAttr -av -k on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -av -k on ".rm";
	setAttr -av -k on ".lm";
	setAttr ".otfna" -type "stringArray" 22 "NURBS Curves" "NURBS Surfaces" "Polygons" "Subdiv Surface" "Particles" "Particle Instance" "Fluids" "Strokes" "Image Planes" "UI" "Lights" "Cameras" "Locators" "Joints" "IK Handles" "Deformers" "Motion Trails" "Components" "Hair Systems" "Follicles" "Misc. UI" "Ornaments"  ;
	setAttr ".otfva" -type "Int32Array" 22 0 1 1 1 1 1
		 1 1 1 0 0 0 0 0 0 0 0 0
		 0 0 0 0 ;
	setAttr -av -k on ".hom";
	setAttr -av -k on ".hodm";
	setAttr -av -k on ".xry";
	setAttr -av -k on ".jxr";
	setAttr -av -k on ".sslt";
	setAttr -av -k on ".cbr";
	setAttr -av -k on ".bbr";
	setAttr -av -k on ".mhl" 16;
	setAttr -k on ".cons" no;
	setAttr -k on ".vac";
	setAttr -av -k on ".hwi";
	setAttr -k on ".csvd";
	setAttr -av -k on ".ta" 3;
	setAttr -av -k on ".tq";
	setAttr -k on ".ts";
	setAttr -av -k on ".etmr";
	setAttr -av -k on ".tmr";
	setAttr -av -k on ".aoon";
	setAttr -av -k on ".aoam";
	setAttr -av -k on ".aora";
	setAttr -k on ".aofr";
	setAttr -av -k on ".aosm";
	setAttr -av -k on ".hff";
	setAttr -av -k on ".hfd";
	setAttr -av -k on ".hfs";
	setAttr -av -k on ".hfe" 125.87412261962891;
	setAttr -av ".hfc" -type "float3" 0.023463 0.079000004 0.079000004 ;
	setAttr -av ".hfc";
	setAttr -av -k on ".hfcr";
	setAttr -av -k on ".hfcg";
	setAttr -av -k on ".hfcb";
	setAttr -av -k on ".hfa" 0.19580419361591339;
	setAttr -av -k on ".mbe";
	setAttr -av -k on ".mbt";
	setAttr -av -k on ".mbsof";
	setAttr -k on ".mbsc";
	setAttr -k on ".mbc";
	setAttr -k on ".mbfa";
	setAttr -k on ".mbftb";
	setAttr -k on ".mbftg";
	setAttr -k on ".mbftr";
	setAttr -av -k on ".mbfta";
	setAttr -k on ".mbfe";
	setAttr -k on ".mbme";
	setAttr -av -k on ".mbcsx";
	setAttr -av -k on ".mbcsy";
	setAttr -av -k on ".mbasx";
	setAttr -av -k on ".mbasy";
	setAttr -av -k on ".blen";
	setAttr -av -k on ".blth";
	setAttr -av -k on ".blfr";
	setAttr -av -k on ".blfa";
	setAttr -av -k on ".blat";
	setAttr -av -k on ".msaa" yes;
	setAttr -av -k on ".aasc" 16;
	setAttr -av -k on ".aasq";
	setAttr -k on ".laa";
	setAttr -k on ".fprt";
	setAttr -k on ".rtfm";
select -ne :renderPartition;
	setAttr -av -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 30 ".st";
	setAttr -cb on ".an";
	setAttr -cb on ".pt";
select -ne :renderGlobalsList1;
	setAttr -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
select -ne :defaultShaderList1;
	setAttr -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 32 ".s";
select -ne :postProcessList1;
	setAttr -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 2 ".p";
select -ne :defaultRenderUtilityList1;
	setAttr -av -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 335 ".u";
select -ne :defaultRenderingList1;
	setAttr -av -k on ".cch";
	setAttr -k on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 118 ".r";
select -ne :defaultTextureList1;
	setAttr -av -k on ".cch";
	setAttr -k on ".fzn";
	setAttr -cb on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 37 ".tx";
lockNode -l 0 -lu 1;
select -ne :initialShadingGroup;
	setAttr -av -k on ".cch";
	setAttr -k on ".fzn";
	setAttr -av -cb on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -k on ".bbx";
	setAttr -k on ".vwm";
	setAttr -k on ".tpv";
	setAttr -k on ".uit";
	setAttr -k on ".mwc";
	setAttr -av -cb on ".an";
	setAttr -cb on ".il";
	setAttr -cb on ".vo";
	setAttr -cb on ".eo";
	setAttr -cb on ".fo";
	setAttr -cb on ".epo";
	setAttr -k on ".ro" yes;
	setAttr -s 1840 ".gn";
select -ne :initialParticleSE;
	setAttr -av -k on ".cch";
	setAttr -k on ".fzn";
	setAttr -av -cb on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -k on ".bbx";
	setAttr -k on ".vwm";
	setAttr -k on ".tpv";
	setAttr -k on ".uit";
	setAttr -k on ".mwc";
	setAttr -av -cb on ".an";
	setAttr -cb on ".il";
	setAttr -cb on ".vo";
	setAttr -cb on ".eo";
	setAttr -cb on ".fo";
	setAttr -cb on ".epo";
	setAttr -k on ".ro" yes;
select -ne :defaultRenderGlobals;
	addAttr -ci true -h true -sn "dss" -ln "defaultSurfaceShader" -dt "string";
	setAttr -av -k on ".cch";
	setAttr -av -cb on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -av -k on ".macc";
	setAttr -av -k on ".macd";
	setAttr -av -k on ".macq";
	setAttr -av -k on ".mcfr" 25;
	setAttr -cb on ".ifg";
	setAttr -av -k on ".clip";
	setAttr -av -k on ".edm";
	setAttr -av -k on ".edl";
	setAttr -av -cb on ".ren";
	setAttr -av -k on ".esr";
	setAttr -av -k on ".ors";
	setAttr -k on ".sdf";
	setAttr -av -k on ".outf" 51;
	setAttr -av -cb on ".imfkey" -type "string" "exr";
	setAttr -av -k on ".gama";
	setAttr -av -k on ".exrc";
	setAttr -av -k on ".expt";
	setAttr -av -cb on ".an";
	setAttr -k on ".ar";
	setAttr -av -k on ".fs";
	setAttr -av -k on ".ef";
	setAttr -av -k on ".bfs";
	setAttr -av -k on ".me";
	setAttr -k on ".se";
	setAttr -av -k on ".be";
	setAttr -av -cb on ".ep";
	setAttr -av -k on ".fec";
	setAttr -av -k on ".ofc";
	setAttr -k on ".ofe";
	setAttr -k on ".efe";
	setAttr -cb on ".oft";
	setAttr -k on ".umfn";
	setAttr -k on ".ufe";
	setAttr -av -cb on ".pff";
	setAttr -av -k on ".peie";
	setAttr -av -cb on ".ifp";
	setAttr -k on ".rv";
	setAttr -av -k on ".comp";
	setAttr -av -k on ".cth";
	setAttr -av -k on ".soll";
	setAttr -av -k on ".sosl";
	setAttr -av -k on ".rd";
	setAttr -av -k on ".lp";
	setAttr -av -k on ".sp";
	setAttr -av -k on ".shs";
	setAttr -av -k on ".lpr";
	setAttr -cb on ".gv";
	setAttr -cb on ".sv";
	setAttr -av -k on ".mm";
	setAttr -av -k on ".npu";
	setAttr -av -k on ".itf";
	setAttr -av -k on ".shp";
	setAttr -cb on ".isp";
	setAttr -av -k on ".uf";
	setAttr -av -k on ".oi";
	setAttr -av -k on ".rut";
	setAttr -av -k on ".mot";
	setAttr -av -k on ".mb";
	setAttr -av -k on ".mbf";
	setAttr -av -k on ".mbso";
	setAttr -av -k on ".mbsc";
	setAttr -av -k on ".afp";
	setAttr -av -k on ".pfb";
	setAttr -av -k on ".pram";
	setAttr -av -k on ".poam";
	setAttr -av -k on ".prlm";
	setAttr -av -k on ".polm";
	setAttr -av -cb on ".prm";
	setAttr -av -cb on ".pom";
	setAttr -k on ".pfrm";
	setAttr -k on ".pfom";
	setAttr -av -k on ".bll";
	setAttr -av -k on ".bls";
	setAttr -av -k on ".smv";
	setAttr -av -k on ".ubc";
	setAttr -av -k on ".mbc";
	setAttr -cb on ".mbt";
	setAttr -av -k on ".udbx";
	setAttr -av -k on ".smc";
	setAttr -av -k on ".kmv";
	setAttr -cb on ".isl";
	setAttr -cb on ".ism";
	setAttr -cb on ".imb";
	setAttr -av -k on ".rlen";
	setAttr -av -k on ".frts";
	setAttr -av -k on ".tlwd";
	setAttr -av -k on ".tlht";
	setAttr -av -k on ".jfc";
	setAttr -cb on ".rsb";
	setAttr -av -k on ".ope";
	setAttr -av -k on ".oppf";
	setAttr -av -k on ".rcp";
	setAttr -av -k on ".icp";
	setAttr -av -k on ".ocp";
	setAttr -cb on ".hbl";
	setAttr ".dss" -type "string" "lambert1";
select -ne :defaultResolution;
	setAttr -av -k on ".cch";
	setAttr -av -k on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -k on ".bnm";
	setAttr -av -k on ".w" 1920;
	setAttr -av -k on ".h" 1080;
	setAttr -av -k on ".pa" 1;
	setAttr -av -k on ".al";
	setAttr -av -k on ".dar" 1.7777777910232544;
	setAttr -av -k on ".ldar";
	setAttr -av -k on ".dpi";
	setAttr -av -k on ".off";
	setAttr -av -k on ".fld";
	setAttr -av -k on ".zsl";
	setAttr -av -k on ".isu";
	setAttr -av -k on ".pdu";
select -ne :defaultColorMgtGlobals;
	setAttr ".cme" no;
	setAttr ".cfp" -type "string" "<MAYA_RESOURCES>/OCIO-configs/Maya2022-default/config.ocio";
select -ne :hardwareRenderGlobals;
	setAttr -av -k on ".cch";
	setAttr -av -cb on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -av -k off -cb on ".ctrs" 256;
	setAttr -av -k off -cb on ".btrs" 512;
	setAttr -av -k off -cb on ".fbfm";
	setAttr -av -k off -cb on ".ehql";
	setAttr -av -k off -cb on ".eams";
	setAttr -av -k off -cb on ".eeaa";
	setAttr -av -k off -cb on ".engm";
	setAttr -av -k off -cb on ".mes";
	setAttr -av -k off -cb on ".emb";
	setAttr -av -k off -cb on ".mbbf";
	setAttr -av -k off -cb on ".mbs";
	setAttr -av -k off -cb on ".trm";
	setAttr -av -k off -cb on ".tshc";
	setAttr -av -k off -cb on ".enpt";
	setAttr -av -k off -cb on ".clmt";
	setAttr -av -k off -cb on ".tcov";
	setAttr -av -k off -cb on ".lith";
	setAttr -av -k off -cb on ".sobc";
	setAttr -av -k off -cb on ".cuth";
	setAttr -av -k off -cb on ".hgcd";
	setAttr -av -k off -cb on ".hgci";
	setAttr -av -k off -cb on ".mgcs";
	setAttr -av -k off -cb on ".twa";
	setAttr -av -k off -cb on ".twz";
	setAttr -av -cb on ".hwcc";
	setAttr -av -cb on ".hwdp";
	setAttr -av -cb on ".hwql";
	setAttr -av -k on ".hwfr" 25;
	setAttr -av -k on ".soll";
	setAttr -av -k on ".sosl";
	setAttr -av -k on ".bswa";
	setAttr -av -k on ".shml";
	setAttr -av -k on ".hwel";
dataStructure -fmt "raw" -as "name=mapManager_suelo:string=value";
dataStructure -fmt "raw" -as "name=IdStruct:int32=ID";
dataStructure -fmt "raw" -as "name=mapManager_restaurantFront:string=value";
dataStructure -fmt "raw" -as "name=notes_walkwayMain_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_small_grass:string=value";
dataStructure -fmt "raw" -as "name=notes_treesB_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_beautyGrassPatchA_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_ground_c_geo:string=value";
dataStructure -fmt "raw" -as "name=mapManager_small_grass:string=value";
dataStructure -fmt "raw" -as "name=notes_floorOrangeGrass_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_sueloC:string=value";
dataStructure -fmt "raw" -as "name=notes_floorScatt:string=value";
dataStructure -fmt "raw" -as "name=notes_strap_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_groundD_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_terracesGrass_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_wildPatchD_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_juneBackYard:string=value";
dataStructure -fmt "raw" -as "name=notes_rightExterior_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_backWall_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_wasteLand_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_baseLeaves:string=value";
dataStructure -fmt "raw" -as "name=mapManager_mountainsRight:string=value";
dataStructure -fmt "raw" -as "name=notes_pPlane6:string=value";
dataStructure -fmt "raw" -as "name=notes_beautyFlowersBedA_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_pPlane3:string=value";
dataStructure -fmt "raw" -as "name=DiffEdge:float=value";
dataStructure -fmt "raw" -as "name=mapManager_walkwayRocket:string=value";
dataStructure -fmt "raw" -as "name=mapManager_geos:string=value";
dataStructure -fmt "raw" -as "name=mapManager_floorScatt:string=value";
dataStructure -fmt "raw" -as "name=notes_grassD_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_tunnel:string=value";
dataStructure -fmt "raw" -as "name=notes_decayFlowerBeds_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_walkwaySpaceland_Main_Leaves:string=value";
dataStructure -fmt "raw" -as "name=mapManager_stoneFloor:string=value";
dataStructure -fmt "raw" -as "name=mapManager_bricksGrounds:string=value";
dataStructure -fmt "raw" -as "name=notes_grassCDecay_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_bricksGround:string=value";
dataStructure -fmt "raw" -as "name=notes_big_back:string=value";
dataStructure -fmt "raw" -as "name=notes_floorGrassA_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_mountainCSC:string=value";
dataStructure -fmt "raw" -as "name=mapManager_bricksTopiary:string=value";
dataStructure -fmt "raw" -as "name=notes_mountainsRight:string=value";
dataStructure -fmt "raw" -as "name=notes_bushes_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_pPlane1:string=value";
dataStructure -fmt "raw" -as "name=notes_restaurantBack:string=value";
dataStructure -fmt "raw" -as "name=mapManager_mountainCSA:string=value";
dataStructure -fmt "raw" -as "name=notes_floorA:string=value";
dataStructure -fmt "raw" -as "name=notes_floorSquare:string=value";
dataStructure -fmt "raw" -as "name=mapManager_grassRightMountains:string=value";
dataStructure -fmt "raw" -as "name=notes_grassScatt:string=value";
dataStructure -fmt "raw" -as "name=notes_bricksTopiary:string=value";
dataStructure -fmt "raw" -as "name=notes_ridePiggy_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_vgFCarouselBed_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_trees:string=value";
dataStructure -fmt "raw" -as "name=notes_wildPatchG_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_slopesGroundGrassB_Combined:string=value";
dataStructure -fmt "raw" -as "name=mapManager_grass_Scatt:string=value";
dataStructure -fmt "raw" -as "name=notes_grassADecay_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_grassDetail_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_grassScatt:string=value";
dataStructure -fmt "raw" -as "name=mapManager_pPlane5:string=value";
dataStructure -fmt "raw" -as "name=notes_frogLeft_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_det:string=value";
dataStructure -fmt "raw" -as "name=mapManager_floor1:string=value";
dataStructure -fmt "raw" -as "name=notes_tilesFloorDet:string=value";
dataStructure -fmt "raw" -as "name=notes_level1A_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_grass_Scatt:string=value";
dataStructure -fmt "raw" -as "name=notes_terraceGrass_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_vgTFicus39:string=value";
dataStructure -fmt "raw" -as "name=mapManager_bricksTopiary_c_geo:string=value";
dataStructure -fmt "raw" -as "name=mapManager_walkwayMain_Flowers:string=value";
dataStructure -fmt "raw" -as "name=mapManager_juneBackYard:string=value";
dataStructure -fmt "raw" -as "name=mapManager_ground_c_geo:string=value";
dataStructure -fmt "raw" -as "name=mapManager_snapshot_Combined:string=value";
dataStructure -fmt "raw" -as "name=mapManager_base_left:string=value";
dataStructure -fmt "raw" -as "name=OrgStruct:float[3]=Origin Point";
dataStructure -fmt "raw" -as "name=notes_beautyGrassPatchD_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_mountains_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_original:string=value";
dataStructure -fmt "raw" -as "name=notes_bricksTopiaryGrass_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_walkwayAreaD_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_bridge_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_ground:string=value";
dataStructure -fmt "raw" -as "name=mapManager_floorConcrete_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_ground:string=value";
dataStructure -fmt "raw" -as "name=mapManager_pPlane2:string=value";
dataStructure -fmt "raw" -as "name=notes_squareRocks_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_slopes:string=value";
dataStructure -fmt "raw" -as "name=notes_decayLeavesCarousel_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_restaurantNextHouse_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_level1A:string=value";
dataStructure -fmt "raw" -as "name=notes_snapshot_Combined2:string=value";
dataStructure -fmt "raw" -as "name=notes_sueloP2:string=value";
dataStructure -fmt "raw" -as "name=notes_degraded:string=value";
dataStructure -fmt "raw" -as "name=notes_Suelo:string=value";
dataStructure -fmt "raw" -as "name=notes_bricksCurbsGrass_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_trees:string=value";
dataStructure -fmt "raw" -as "name=notes_wildPatchH_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_ground03_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_grass_c_geo:string=value";
dataStructure -fmt "raw" -as "name=mapManager_floor:string=value";
dataStructure -fmt "raw" -as "name=notes_scatterGround:string=value";
dataStructure -fmt "raw" -as "name=notes_base_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_grassB_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_decayLeaves_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_scatt:string=value";
dataStructure -fmt "raw" -as "name=notes_tunnel:string=value";
dataStructure -fmt "raw" -as "name=f_3:float[3]=value";
dataStructure -fmt "raw" -as "name=faceConnectMarkerStructure:bool=faceConnectMarker:string[200]=faceConnectOutputGroups";
dataStructure -fmt "raw" -as "name=notes_slopesC_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_floorOrangeConcrete_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_circular:string=value";
dataStructure -fmt "raw" -as "name=notes_base_hojas:string=value";
dataStructure -fmt "raw" -as "name=notes_grassA_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_sueloA8:string=value";
dataStructure -fmt "raw" -as "name=notes_railes:string=value";
dataStructure -fmt "raw" -as "name=mapManager_slopesMountainsGrass_Combined:string=value";
dataStructure -fmt "raw" -as "name=notes_mountainsCSA_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_scatterGround:string=value";
dataStructure -fmt "raw" -as "name=notes_groundA_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_flowersMain_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_midgroundPlane:string=value";
dataStructure -fmt "raw" -as "name=notes_midground_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_groundRocks:string=value";
dataStructure -fmt "raw" -as "name=FBXFastExportSetting_MB:string=19424";
dataStructure -fmt "raw" -as "name=mapManager_walkwaySpaceland_Main_Leaves:string=value";
dataStructure -fmt "raw" -as "name=notes_left_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_new_sand:string=value";
dataStructure -fmt "raw" -as "name=notes_terracesGrasStairs_parShape:string=value";
dataStructure -fmt "raw" -as "name=Blur3dMetaData:string=Blur3dValue";
dataStructure -fmt "raw" -as "name=mapManager_rocks:string=value";
dataStructure -fmt "raw" -as "name=mapManager_baseScatter:string=value";
dataStructure -fmt "raw" -as "name=notes_hotelBack_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_levelUnoB_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_sand_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_cheat_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_pPlane:string=value";
dataStructure -fmt "raw" -as "name=notes_backgroundPlane:string=value";
dataStructure -fmt "raw" -as "name=mapManager_pPlane1:string=value";
dataStructure -fmt "raw" -as "name=mapManager_sueloC:string=value";
dataStructure -fmt "raw" -as "name=mapManager_level1A:string=value";
dataStructure -fmt "raw" -as "name=notes_leaves_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_levelUnoA_parShape:string=value";
dataStructure -fmt "raw" -as "name=Offset:float[3]=value";
dataStructure -fmt "raw" -as "name=notes_terracesFront_parShape:string=value";
dataStructure -fmt "raw" -as "name=externalContentTablZ:string=nodZ:string=key:string=upath:uint32=upathcrc:string=rpath:string=roles";
dataStructure -fmt "raw" -as "name=notes_groundB_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_decayGrassPatchC_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_polySurface56:string=value";
dataStructure -fmt "raw" -as "name=notes_sueloP1:string=value";
dataStructure -fmt "raw" -as "name=mapManager_riverSide:string=value";
dataStructure -fmt "raw" -as "name=notes_terracesFlowers_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_restaurantFront:string=value";
dataStructure -fmt "raw" -as "name=notes_throwbotLeft_scatt:string=value";
dataStructure -fmt "raw" -as "name=notes_mountainsCSC_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_concretePath_c_geo:string=value";
dataStructure -fmt "raw" -as "name=mapManager_floorSquare:string=value";
dataStructure -fmt "raw" -as "name=notes_base:string=value";
dataStructure -fmt "raw" -as "name=notes_bricksTopiary_c_geo:string=value";
dataStructure -fmt "raw" -as "name=mapManager_concretePath_c_geo:string=value";
dataStructure -fmt "raw" -as "name=mapManager_suelofuente:string=value";
dataStructure -fmt "raw" -as "name=mapManager_slopesGroundGrassD_Combined:string=value";
dataStructure -fmt "raw" -as "name=notes_vegetation_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_restaurantBack_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_walkwaySquareFlowers_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_leavesDecay_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_grass_c_geo1:string=value";
dataStructure -fmt "raw" -as "name=notes_ferns_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_floor:string=value";
dataStructure -fmt "raw" -as "name=notes_sidewalkGrassB_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_decayGrassPatchB_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_holeRock_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_base_right:string=value";
dataStructure -fmt "raw" -as "name=mapManager_walkwayRocket_flowers:string=value";
dataStructure -fmt "raw" -as "name=notes_pPlane5:string=value";
dataStructure -fmt "raw" -as "name=notes_entrance_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_riverSide:string=value";
dataStructure -fmt "raw" -as "name=notes_treesRocksAnimalHome_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_treesA_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_slopesB_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_railwayGrass_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_slopesGroundGrassC_Combined:string=value";
dataStructure -fmt "raw" -as "name=notes_decayLeavesFlowerBed_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_terracesSuelo:string=value";
dataStructure -fmt "raw" -as "name=mapManager_backgroundPlane:string=value";
dataStructure -fmt "raw" -as "name=notes_level1B_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_grassCenter_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_snapshot_Combined2:string=value";
dataStructure -fmt "raw" -as "name=notes_baseScatter:string=value";
dataStructure -fmt "raw" -as "name=notes_walkwayAreaC_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_groundWoods_c_geo1:string=value";
dataStructure -fmt "raw" -as "name=notes_mountainTrail_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_grassLeftMountains_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_slopesMountainsGrass_Combined:string=value";
dataStructure -fmt "raw" -as "name=mapManager_sueloP2:string=value";
dataStructure -fmt "raw" -as "name=notes_terracesRight_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_pPlane2:string=value";
dataStructure -fmt "raw" -as "name=notes_trees_left:string=value";
dataStructure -fmt "raw" -as "name=notes_pPlane4:string=value";
dataStructure -fmt "raw" -as "name=notes_stairs_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_snapshot_floor:string=value";
dataStructure -fmt "raw" -as "name=notes_terraces_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_snapshot_Combined:string=value";
dataStructure -fmt "raw" -as "name=mapManager_drawBridge_physPivot:string=value";
dataStructure -fmt "raw" -as "name=notes_widlPatchB_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_path:string=value";
dataStructure -fmt "raw" -as "name=notes_square_floor:string=value";
dataStructure -fmt "raw" -as "name=notes_base_left:string=value";
dataStructure -fmt "raw" -as "name=notes_suelo:string=value";
dataStructure -fmt "raw" -as "name=mapManager_stairs_c_geo:string=value";
dataStructure -fmt "raw" -as "name=mapManager_rocskLeftPLA:string=value";
dataStructure -fmt "raw" -as "name=notes_grassRightMountains_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_grassCampfire_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_leftSpecific_parShape:string=value";
dataStructure -fmt "raw" -as "name=RenderSettings:string=preset";
dataStructure -fmt "raw" -as "name=notes_grassJuneBackYard_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_pPlane:string=value";
dataStructure -fmt "raw" -as "name=notes_floorConcrete_c_geo:string=value";
dataStructure -fmt "raw" -as "name=mapManager_road_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_floor1:string=value";
dataStructure -fmt "raw" -as "name=notes_terracesGrassDetail_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_floorOrangeConcrete_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_beautyGrassPatchC_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_slideSundaeRight_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_flowersSquare:string=value";
dataStructure -fmt "raw" -as "name=mapManager_baseForest:string=value";
dataStructure -fmt "raw" -as "name=mapManager_rockSignRollo:string=value";
dataStructure -fmt "raw" -as "name=mapManager_throwbotLeft_scatt:string=value";
dataStructure -fmt "raw" -as "name=mapManager_baseScatt:string=value";
dataStructure -fmt "raw" -as "name=mapManager_floorA:string=value";
dataStructure -fmt "raw" -as "name=notes_det:string=value";
dataStructure -fmt "raw" -as "name=notes_decayGrassPatchA_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_frogL_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_Suelo:string=value";
dataStructure -fmt "raw" -as "name=faceConnectOutputStructure:bool=faceConnectOutput:string[200]=faceConnectOutputAttributes:string[200]=faceConnectOutputGroups";
dataStructure -fmt "raw" -as "name=notes_suelofuente:string=value";
dataStructure -fmt "raw" -as "name=notes_tunnelParkEntrance_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_walkwayRocket:string=value";
dataStructure -fmt "raw" -as "name=BilateralStructure:bool=right:bool=center:bool=left";
dataStructure -fmt "raw" -as "name=notes_slideSundaeLeft_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_small:string=value";
dataStructure -fmt "raw" -as "name=notes_slopesGroundGrassA_Combined:string=value";
dataStructure -fmt "raw" -as "name=notes_treesRocksHA_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_terracesTrees_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_baseScatt:string=value";
dataStructure -fmt "raw" -as "name=notes_slopesCDetail_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_floor_c_geo:string=value";
dataStructure -fmt "raw" -as "name=mapManager_sueloA8:string=value";
dataStructure -fmt "raw" -as "name=mapManager_snapshot_Combined1:string=value";
dataStructure -fmt "raw" -as "name=notes_grass:string=value";
dataStructure -fmt "raw" -as "name=mapManager_groundPlane_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_slabsAndStairsGrass_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_bushesA_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_floor_flowers:string=value";
dataStructure -fmt "raw" -as "name=mapManager_trees_left:string=value";
dataStructure -fmt "raw" -as "name=notes_wildPatchDegraded_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_levelUnoC_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_base_right:string=value";
dataStructure -fmt "raw" -as "name=notes_walkwayCircular_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_square_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_square_ground:string=value";
dataStructure -fmt "raw" -as "name=notes_chocolateFountain_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_walkwayAreaCorner_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_throwbotLeftScatt:string=value";
dataStructure -fmt "raw" -as "name=notes_stoneFloor:string=value";
dataStructure -fmt "raw" -as "name=notes_sueloA:string=value";
dataStructure -fmt "raw" -as "name=notes_slopesGroundGrassD_Combined1:string=value";
dataStructure -fmt "raw" -as "name=notes_frogEntrance_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_baseForest:string=value";
dataStructure -fmt "raw" -as "name=notes_grassC_parShape:string=value";
dataStructure -fmt "raw" -as "name=f_1:float=value";
dataStructure -fmt "raw" -as "name=notes_carouselStairs_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_floorCampfire:string=value";
dataStructure -fmt "raw" -as "name=mapManager_arbustosScatt:string=value";
dataStructure -fmt "raw" -as "name=notes_mountainsCSB_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_path:string=value";
dataStructure -fmt "raw" -as "name=notes_terraceBush_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_mainStreetMainstreetTrees04:string=value";
dataStructure -fmt "raw" -as "name=mapManager_grass_floor:string=value";
dataStructure -fmt "raw" -as "name=notes_square_ground:string=value";
dataStructure -fmt "raw" -as "name=mapManager_pPlane4:string=value";
dataStructure -fmt "raw" -as "name=notes_sueloB:string=value";
dataStructure -fmt "raw" -as "name=notes_stoneFloor_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_backWall_c_geo:string=value";
dataStructure -fmt "raw" -as "name=mapManager_slopesGroundGrassA_Combined:string=value";
dataStructure -fmt "raw" -as "name=notes_rockCheated_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_restaurantFront_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_slideSundaeRightScatt:string=value";
dataStructure -fmt "raw" -as "name=mapManager_sueloP1:string=value";
dataStructure -fmt "raw" -as "name=notes_heroesChoice_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_bricksFence_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_floor_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_snapshot_CombinedGrass:string=value";
dataStructure -fmt "raw" -as "name=notes_floor_flowers:string=value";
dataStructure -fmt "raw" -as "name=mapManager_circular:string=value";
dataStructure -fmt "raw" -as "name=notes_groundWoods_c_geo1:string=value";
dataStructure -fmt "raw" -as "name=mapManager_level1A_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_slopes_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_scatt:string=value";
dataStructure -fmt "raw" -as "name=notes_groundPlane_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_mountainCSC:string=value";
dataStructure -fmt "raw" -as "name=mapManager_terracesSuelo:string=value";
dataStructure -fmt "raw" -as "name=notes_road_c_geo:string=value";
dataStructure -fmt "raw" -as "name=ComboStructure:bool=shape";
dataStructure -fmt "raw" -as "name=mapManager_groundRocks:string=value";
dataStructure -fmt "raw" -as "name=mapManager_bricksTielMainStreet_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_walkwayMain_Flowers:string=value";
dataStructure -fmt "raw" -as "name=notes_vgtCampfire_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_sueloA9:string=value";
dataStructure -fmt "raw" -as "name=notes_arbustosScatt:string=value";
dataStructure -fmt "raw" -as "name=mapManager_sueloB:string=value";
dataStructure -fmt "raw" -as "name=notes_sand_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_sueloProvi3:string=value";
dataStructure -fmt "raw" -as "name=TifLocation:string=Path";
dataStructure -fmt "raw" -as "name=notes_wildPatchA_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_pPlane6:string=value";
dataStructure -fmt "raw" -as "name=notes_slopesGroundGrassD_Combined:string=value";
dataStructure -fmt "raw" -as "name=mapManager_flowersSquare:string=value";
dataStructure -fmt "raw" -as "name=notes_curbsGardenGrass_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_grassBeauty_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_mountainCSA:string=value";
dataStructure -fmt "raw" -as "name=notes_polySurface56:string=value";
dataStructure -fmt "raw" -as "name=mapManager_floorCampfire:string=value";
dataStructure -fmt "raw" -as "name=mapManager_restaurantBack:string=value";
dataStructure -fmt "raw" -as "name=notes_decayGrassesCenter_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_original:string=value";
dataStructure -fmt "raw" -as "name=notes_bricksTielMainStreet_c_geo:string=value";
dataStructure -fmt "raw" -as "name=DiffArea:float=value";
dataStructure -fmt "raw" -as "name=notes_riverside_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_floorFlower:string=value";
dataStructure -fmt "raw" -as "name=notes_walkwayRocket_flowers:string=value";
dataStructure -fmt "raw" -as "name=mapManager_new_sand:string=value";
dataStructure -fmt "raw" -as "name=notes_walkwayArea_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_ground03_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_wildPatchF_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_centerStreetGrass_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_base_hojas:string=value";
dataStructure -fmt "raw" -as "name=NameAndID:string=name:int32=ID";
dataStructure -fmt "raw" -as "name=mapManager_grassGround_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_grassBase:string=value";
dataStructure -fmt "raw" -as "name=notes_juneNbhHouseE_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_slideSundaeRightScatt:string=value";
dataStructure -fmt "raw" -as "name=notes_concretesGrass_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_big_back:string=value";
dataStructure -fmt "raw" -as "name=notes_flowersRightLeft_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_wildPatchC_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_square_floor:string=value";
dataStructure -fmt "raw" -as "name=mapManager_sueloA:string=value";
dataStructure -fmt "raw" -as "name=notes_drawBridge_physPivot:string=value";
dataStructure -fmt "raw" -as "name=notes_decayGrassPatchD_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_barbacueHouseFront_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_background_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_level1B_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_flowersHA_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_levelC:string=value";
dataStructure -fmt "raw" -as "name=notes_trees_left1:string=value";
dataStructure -fmt "raw" -as "name=Curvature:float=mean:float=gaussian:float=ABS:float=RMS";
dataStructure -fmt "raw" -as "name=notes_walkwayAreaB_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_mountainCSB:string=value";
dataStructure -fmt "raw" -as "name=notes_grassRightMountains:string=value";
dataStructure -fmt "raw" -as "name=notes_grassGround_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_beautyGrassPatchB_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_base:string=value";
dataStructure -fmt "raw" -as "name=notes_snapshot_Combined1:string=value";
dataStructure -fmt "raw" -as "name=notes_baseLeaves:string=value";
dataStructure -fmt "raw" -as "name=notes_riverSideground:string=value";
dataStructure -fmt "raw" -as "name=mapManager_curbsGarden_c_geo:string=value";
dataStructure -fmt "raw" -as "name=notes_bricksGrounds:string=value";
dataStructure -fmt "raw" -as "name=notes_rockSignRollo_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_sidewalkGrass_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_right_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_curbsGarden_c_geo:string=value";
dataStructure -fmt "raw" -as "name=mapManager_trees_left1:string=value";
dataStructure -fmt "raw" -as "name=notes_rocskLeftPLA:string=value";
dataStructure -fmt "raw" -as "name=notes_rocks:string=value";
dataStructure -fmt "raw" -as "name=notes_geos:string=value";
dataStructure -fmt "raw" -as "name=OffStruct:float=Offset";
dataStructure -fmt "raw" -as "name=notes_small:string=value";
dataStructure -fmt "raw" -as "name=keyValueStructure:string=value";
dataStructure -fmt "raw" -as "name=notes_bricksFence_c_geo:string=value";
dataStructure -fmt "raw" -as "name=mapManager_grasses:string=value";
dataStructure -fmt "raw" -as "name=notes_testMode_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_snapshot_CombinedGrass:string=value";
dataStructure -fmt "raw" -as "name=mapManager_grass:string=value";
dataStructure -fmt "raw" -as "name=notes_stoneFloorGrass_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_leaves:string=value";
dataStructure -fmt "raw" -as "name=notes_walkwaySquare_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_fountainHA_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_grass_c_geo1:string=value";
dataStructure -fmt "raw" -as "name=notes_groundC_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_grassBase:string=value";
dataStructure -fmt "raw" -as "name=mapManager_levelC:string=value";
dataStructure -fmt "raw" -as "name=notes_grass_floor:string=value";
dataStructure -fmt "raw" -as "name=idStructure:int32=ID";
dataStructure -fmt "raw" -as "name=mapManager_amp_lyref_cmp0010_layGround:string=value";
dataStructure -fmt "raw" -as "name=notes_walkwayRocket_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_pPlane3:string=value";
dataStructure -fmt "raw" -as "name=notes_center_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_trees_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_mountainCSB:string=value";
dataStructure -fmt "raw" -as "name=notes_rockSignRollo:string=value";
dataStructure -fmt "raw" -as "name=FBXFastExportSetting_FBX:string=54";
dataStructure -fmt "raw" -as "name=mapManager_slopesGroundGrassD_Combined1:string=value";
dataStructure -fmt "raw" -as "name=mapManager_snapshot_floor:string=value";
dataStructure -fmt "raw" -as "name=mapManager_floorFlower:string=value";
dataStructure -fmt "raw" -as "name=mapManager_leaves:string=value";
dataStructure -fmt "raw" -as "name=notes_fountainRight_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_slopes:string=value";
dataStructure -fmt "raw" -as "name=mapManager_tilesFloorDet:string=value";
dataStructure -fmt "raw" -as "name=notes_rockTerraces_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_railes:string=value";
dataStructure -fmt "raw" -as "name=notes_grasses:string=value";
dataStructure -fmt "raw" -as "name=notes_wildPatchE_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_grass_c_geo:string=value";
dataStructure -fmt "raw" -as "name=mapManager_riverSideground:string=value";
dataStructure -fmt "raw" -as "name=mapManager_slopesGroundGrassB_Combined:string=value";
dataStructure -fmt "raw" -as "name=mapManager_strap_c_geo:string=value";
dataStructure -fmt "raw" -as "name=mapManager_degraded:string=value";
dataStructure -fmt "raw" -as "name=mapManager_bricksGround:string=value";
dataStructure -fmt "raw" -as "name=notes_amp_lyref_cmp0010_layGround:string=value";
dataStructure -fmt "raw" -as "name=notes_midgroundPlane:string=value";
dataStructure -fmt "raw" -as "name=mapManager_slopesGroundGrassC_Combined:string=value";
dataStructure -fmt "raw" -as "name=mapManager_throwbotLeftScatt:string=value";
dataStructure -fmt "raw" -as "name=notes_road_parShape:string=value";
dataStructure -fmt "raw" -as "name=mapManager_sueloA9:string=value";
dataStructure -fmt "raw" -as "name=notes_grassBDecay_parShape:string=value";
dataStructure -fmt "raw" -as "name=notes_vgGroundB_parShape:string=value";
// End of virus_sample.ma
