name: Upload Python Package

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        fetch-depth: 0
        ref: main
    - uses: olegtarasov/get-tag@v2.1.3
      id: get_tag_name
      with:
        tagRegex: "v(?<version>.*)"
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install -U pip poetry nox
        poetry --version
        poetry build
    # Note that we don't need credentials.
    # We rely on https://docs.pypi.org/trusted-publishers/.
    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist
    - name: make Maya Mod
      id: make_maya_mod
      run: |
        nox -s make-zip -- --version ${{ steps.get_tag_name.outputs.version }}
    - name: Generate changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@main
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        filter-author: (|dependabot|renovate\\[bot\\]|dependabot\\[bot\\]|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
        template: |
          ## Bugs
          {{fix}}
          ## Feature
          {{feat}}
          ## Improve
          {{refactor,perf,clean}}
          ## Misc
          {{chore,style,ci||🔶 Nothing change}}
          ## Unknown
          {{__unknown__}}
    - uses: ncipollo/release-action@v1
      with:
        artifacts: ".zip/maya_umbrella-*.zip"
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        body: |
          Comparing Changes: ${{ steps.changelog.outputs.compareurl }}

          ${{ steps.changelog.outputs.changelog }}
